apiVersion: v1
kind: Service
metadata:
  name: mysql-pm
  namespace: external
  labels:
    app: mysql-pm
spec:
  type: NodePort
  ports:
  - port: 3306
    name: mysql-pm
    nodePort: 31002
#  clusterIP: None
  selector:
    app: mysql-pm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-pm
  namespace: external
spec:
  serviceName: "mysql-pm-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-pm
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-pm
        image: mysql:5.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Bdp@2019
        - name: MYSQL_USER
          value: ertong
        - name: MYSQL_USER_PASSWORD
          value: Bdp@2019
        ports:
        - containerPort: 3306
          name: mysql-pm
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi
