apiVersion: v1
kind: Service
metadata:
  name: mysql-nlp
  namespace: www-biosino-org
  labels:
    app: mysql-nlp
spec:
  type: NodePort
  ports:
  - port: 3306
    name: mysql-pm
    nodePort: 31006
#  clusterIP: None
  selector:
    app: mysql-nlp
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-nlp
  namespace: www-biosino-org
spec:
  serviceName: "mysql-nlp"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-nlp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-nlp
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_USER
          value: ertong
        - name: MYSQL_USER_PASSWORD
          value: Bdp@2019
        ports:
        - containerPort: 3306
          name: mysql-nlp
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi
